import swaggerUi from "swagger-ui-express";
import swaggerJsdoc from "swagger-jsdoc";
import listEndpoints from "express-list-endpoints";

/**
 * Base Swagger (OpenAPI 3) configuration.
 * This defines general API metadata and tells swagger-jsdoc
 * where to scan for @swagger annotations.
 */
const swaggerOptions = {
  definition: {
    openapi: "3.0.0",
    info: {
      title: process.env.APP_NAME ?? "Backend-Mid-Specialism",
      version: process.env.APP_VERSION ?? "0.0.1",
      description: "API documentation",
    },
    components: {
      securitySchemes: {
        bearerAuth: {
          type: "http",
          scheme: "bearer",
          bearerFormat: "JWT",
        },
      },
    },
  },
  apis: ["./src/routers/**/*.js", "./src/routers/*.js", "./src/docs/*.yaml"],
};

/**
 * Default OpenAPI operation stub.
 *
 * Used when an endpoint has NO @swagger documentation.
 * Ensures that every route still appears in Swagger UI.
 */
const openApiEndpointSpecStub = {
  tags: ["Undocumented"],
  responses: {
    200: { description: "OK" },
  },
};

const swaggerSpec = swaggerJsdoc(swaggerOptions);
const swaggerServe = swaggerUi.serve;

/**
 * Convert Express route params to OpenAPI path params.
 *
 * Examples:
 * - /api/events/:id -> /api/events/{id}
 * - /api/users/:userId/orders/:orderId -> /api/users/{userId}/orders/{orderId}
 *
 * @param {string} path
 * @returns {string}
 */
function expressPathToOpenApiPath(path) {
  return path.replace(/:([A-Za-z0-9_]+)/g, "{$1}");
}

/**
 * Generates OpenAPI "paths" object automatically
 * by inspecting the Express app router stack.
 *
 * Undocumented routes are converted into OpenAPI-compatible
 * path syntax so they can merge correctly with manually
 * documented @swagger definitions.
 *
 * @param {import("express").Application} app
 * @returns {object}
 *
 * Example output:
 * {
 *   "/api/users": {
 *     get: { ... },
 *     post: { ... }
 *   }
 * }
 */
const generateOpenApiSpecs = (app) => {
  const specs = {};

  for (const ep of listEndpoints(app)) {
    const normalizedPath = expressPathToOpenApiPath(ep.path);

    specs[normalizedPath] ??= {};

    for (const method of ep.methods) {
      const m = method.toLowerCase();

      specs[normalizedPath][m] ??= {
        ...openApiEndpointSpecStub,
        summary: `Undocumented: ${method} ${normalizedPath}`,
      };
    }
  }

  return specs;
};

/**
 * Initializes Swagger UI with merged specification.
 *
 * Steps:
 *  1. Auto-generate path specs from Express routes
 *  2. Merge with swagger-jsdoc output
 *     (Manual @swagger docs override auto stubs)
 *  3. Mount Swagger UI at /docs
 *
 * @param {import("express").Application} app - Express application instance
 */
const swaggerSetup = (app) => {
  const autoGeneratedSpecs = generateOpenApiSpecs(app);

  // Start from the jsdoc spec (source of truth)
  const mergedSpec = { ...swaggerSpec };
  mergedSpec.paths ??= {};

  // Only add stubs where docs are missing
  for (const [path, ops] of Object.entries(autoGeneratedSpecs)) {
    mergedSpec.paths[path] ??= {};

    for (const [method, opSpec] of Object.entries(ops)) {
      mergedSpec.paths[path][method] ??= opSpec;
    }
  }

  app.get("/docs-json", (req, res) => {
    res.setHeader("Content-Type", "application/json");
    res.send(mergedSpec);
  });

  app.use("/docs", swaggerServe, swaggerUi.setup(mergedSpec));
};

export default swaggerSetup;
